### ISSUE TITLE
Similar Project

### ISSUE THREAD

**Issue by pwhelan** [iwai/react-resque#1]
For what it's worth I created my own React based Resque server: https://github.com/pwhelan/randr.

**Comment by iwai** [comment]
@pwhelan Your project is a great, but i wanted all of event model, than fork model.

**Comment by pwhelan** [comment]
It's actually a worker pool. The reason for it is that if your workers are CPU intensive in any way it'll starve all the workers running in your server. I was thinking of adding some kind of hybrid worker pool model so that some queues/workers could run in the main thread, or fork every time but did not get around to it.

**Comment by iwai** [comment]
In my case, very network IO processing are many, in order to cost hypertrophy of the fork, because the CPU is not fully utilized, we have to handle all of the processing in the event loop.

> hybrid worker pool model

nice idea!!

**Comment by pwhelan** [comment]
If your workload is I/O heavy going with an event model is the way to go.
